### PR TITLE
Add support for TSL UMDv5

### PR DESCRIPTION
**Pull request by NoahCallaway**
Adds support for both TCP and UDP versions of the UMDv5 protocol.

### CODE REVIEW

**Comment by josephdadams** [comment]
@krocheck is `package-lock.json` needed here?

**Comment by krocheck** [comment]
nope

**Comment by josephdadams** [comment]
@NoahCallaway please remove `package-lock.json` and I can get this merged

**Comment by NoahCallaway** [comment]
Done! Thanks 😄

**Pull request merged**
