### PR TITLE
Fixes for TSL V4, etc

### PR DESCRIPTION
**Pull request by roddypratt**
My first contribution to Companion so please be gentle.  

* Fixes TSL V4 (correct checksums, etc)
* Works correctly with addresses >= 10
* Adds commands allowing multiple tallies to be active simultaneously. 
* Reformatted according to guidelines, and lightly refactored.

### CODE REVIEW

**Comment by roddypratt** [comment]
Forgot to mention, tested with this, which I've just added on github. 
https://github.com/roddypratt/tallyview

**Comment by JeffreyDavidsz** [comment]
My friend we use tabs instead of spaces, please adjust your editor :-)

**Comment by roddypratt** [comment]
My bad. I read the DEVELOPER doc but misinterpreted it. :( 

The open issues on this repo can probably be closed now?

**Comment by JeffreyDavidsz** [comment]
Yep thank you!

**Pull request merged**
